# Generated by Django 2.0.6 on 2018-06-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180625_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
    ]
